# -*- coding: utf-8 -*-
"""HW4Question1-DecisionTreeClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jS35m8z8TqfSPcZ7FlDbJDrpFsaDOB8x
"""

#Q1

pip install numpy

pip install pandas

pip install scikit-learn

import numpy as np
import pandas as pd
import sklearn

from google.colab import files
data_to_load = files.upload()

import io
df = pd.read_csv(io.BytesIO(data_to_load['census.csv']))

df.head()

df.columns

from sklearn.preprocessing import LabelEncoder

#transforming string to numerical data
le=LabelEncoder()
i=[1,2,3,4,5,6,7,11,12]
for i in df:
    df[i]=le.fit_transform(df[i])

df.head()

# i)

from sklearn.model_selection import train_test_split

X=df.iloc[:,0:12].values
y=df.iloc[:,12].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40,random_state=101)

#ii)

from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier(criterion='gini')
model.fit(X_train,y_train)


if model.predict([[22	,7	,9,	4,1	,1,	4,	1	,25,	0	,39	,38]])==1:
    print("yes its over 50,000")
else:
    print("no its not over 50,000")

#iii)

from sklearn import tree
import graphviz
dot_data = tree.export_graphviz(model,max_depth=4,filled=True, rounded=True,special_characters=True)  
graph = graphviz.Source(dot_data)

graph



# iv)

model.score(X_test,y_test)

