# -*- coding: utf-8 -*-
"""HW4Q3-DecisionTreeClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16c0T0W0DVvYnK6t5kHj5L_58sK8S_MSA
"""

#Q3

pip install numpy

pip install pandas

pip install scikit-learn

import numpy as np
import pandas as pd
import sklearn

from google.colab import files
data_to_load = files.upload()

import io
df = pd.read_csv(io.BytesIO(data_to_load['Gerber.csv']))

print(df)

#i)

df.columns

from sklearn.model_selection import train_test_split

X=df.iloc[:,[3,4,5,6,7]]
y=df.iloc[:,2].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=101)

#ii)

from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier(criterion='gini')
model.fit(X_train,y_train)
print(model.predict([[0,1,0,0,0]]))

#iii)

from sklearn import tree
import graphviz
dot_data = tree.export_graphviz(model,max_depth=5,filled=True, rounded=True,special_characters=True)  
graph = graphviz.Source(dot_data)

graph

#vi)

X=df.iloc[:,[0,3,4,5,6,7]]
y=df.iloc[:,2].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=101)

model=DecisionTreeClassifier(criterion='gini')
model.fit(X_train,y_train)

from sklearn import tree
import graphviz
dot_data = tree.export_graphviz(model,max_depth=6,filled=True, rounded=True,special_characters=True)  
graph = graphviz.Source(dot_data)

graph

