# -*- coding: utf-8 -*-
"""migration pattern using PrefixSpan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bpG4lIPxCoNA9AWhyjN9JxwHSVNFeU3j
"""

#for migration pattern
#!pip install spmf

!pip install -U prefixspan



"""#Importing data"""

from google.colab import drive

drive.mount('/content/drive')

"""#Importing libraries"""

# Commented out IPython magic to ensure Python compatibility.

# For Panel Data Analysis
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('mode.chained_assignment', None)

# For Random seed values
from random import randint

# For Scientifc Python
from scipy import stats

# For datetime
import datetime
from datetime import datetime as dt

# For Data Visualization
import plotly.graph_objects as go
import matplotlib.pyplot as plt
# %matplotlib inline
from matplotlib.gridspec import GridSpec
import seaborn as sns

# For Preprocessing
from sklearn.preprocessing import StandardScaler

# For Data Modeling
from sklearn.cluster import KMeans
from sklearn import datasets
# To Disable Warnings
import warnings
warnings.filterwarnings(action = "ignore")

#for modeling migratoin pattern
from prefixspan import PrefixSpan
#from spmf import Spmf

path="/content/drive/MyDrive/Thesis/clusters in each period.csv"
ClusterPattern = pd.read_csv(path)
ClusterPattern=ClusterPattern[['period1','period2','period3','period4']]
ClusterPattern.head()

# f = open("/content/drive/MyDrive/Thesis/ClusterPattern.txt", "r")
# print(np.loadtxt(f))

ClusterPattern=ClusterPattern.to_numpy()

p= PrefixSpan(ClusterPattern)

FrequentPattern=p.topk(300)
print (FrequentPattern)

"""#Migratoin pattern"""

# spmf = Spmf("PrefixSpan", input_filename="ClusterPattern.txt",
#             output_filename="output.txt", arguments=[0.7, 5])
# spmf.run()
# print(spmf.to_pandas_dataframe(pickle=True))

# from google.colab import files
# spmf.to_csv('spmf.csv') 
# files.download("spmf.csv")


# #spmf.to_csv("output.csv")

df = pd.DataFrame(FrequentPattern, columns = ['Num of times repeated','Pattern'])

print(df)
print(type(df))

from google.colab import files
df.to_csv('df.csv') 
files.download("df.csv")